language: cpp
compiler: gcc
services: docker
dist: trusty
cache:
    ccache: true
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
    - sudo pip install --upgrade conan
    - conan user
install:
    - docker pull remyabel/i686-cross-gcc
script:
    - docker run -it -v "$TRAVIS_BUILD_DIR":/app remyabel/i686-cross-gcc /bin/sh -c "mkdir -p /app/obj; make -C /app main"
    - eval "${MATRIX_EVAL}"
    - cd "$TRAVIS_BUILD_DIR" && cd test && mkdir build && cd build
    - conan install ..
    - cmake ..
    - cmake --build . -- -j2
    - ./bin/cpp-i386-kernel-tests

notifications:
    email: false
