language: cpp
compiler: gcc
dist: trusty
cache:
    ccache: true
    directories:
        - $HOME/cross-install
matrix:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
    - sudo apt-get install -y nasm
install:
    - bash build-toolchain.sh
    - export PATH="$HOME/cross-install/bin:$PATH" CC="i686-elf-gcc" CXX="i686-elf-g++"

script:
    - cd "$TRAVIS_BUILD_DIR" && mkdir -p obj && make main
    - cd test && wget https://github.com/catchorg/Catch2/releases/download/v2.4.0/catch.hpp 
    - eval "${MATRIX_EVAL}"
    - cd "$TRAVIS_BUILD_DIR" && make HOST_CXX="${CXX}" test

notifications:
    email: false
